# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default=b'N/A', max_length=100)),
                ('locatie', models.CharField(max_length=100)),
                ('aantal_plaatsen', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='reservatie',
            name='for_zaal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservatie_open_cv.Zaal'),
        ),
        migrations.AddField(
            model_name='reservatie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
