# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservatie_open_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaal',
            name='naam',
            field=models.CharField(max_length=100),
        ),
    ]
