# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('reservatie_open_cv', '0002_auto_20170727_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('face_id', models.IntegerField(db_index=True, default=9999999, unique=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='reservatie',
            name='user',
        ),
        migrations.AlterField(
            model_name='reservatie',
            name='for_zaal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaties', to='reservatie_open_cv.Zaal'),
        ),
        migrations.AddField(
            model_name='reservatie',
            name='face_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservatie_open_cv.FaceUser'),
            preserve_default=False,
        ),
    ]
